export const SPECTRUMS: [string, string][] = [
  // Classic
  ["Hot", "Cold"],
  ["Soft", "Hard"],
  ["Boring", "Exciting"],
  ["Slow", "Fast"],
  ["Quiet", "Loud"],
  ["Light", "Heavy"],
  ["Simple", "Complex"],
  ["Old", "New"],
  ["Cheap", "Expensive"],
  ["Small", "Big"],
  ["Weak", "Strong"],
  ["Ugly", "Beautiful"],
  ["Sad", "Happy"],
  ["Dangerous", "Safe"],
  ["Dry", "Wet"],
  ["Dark", "Bright"],
  ["Short", "Tall"],
  ["Narrow", "Wide"],
  ["Shallow", "Deep"],
  ["Empty", "Full"],

  // Opinion
  ["Underrated", "Overrated"],
  ["Villain", "Hero"],
  ["Trashy", "Classy"],
  ["Guilty pleasure", "Proudly love"],
  ["Forgettable", "Iconic"],
  ["Mainstream", "Niche"],
  ["Cringe", "Cool"],
  ["Basic", "Unique"],
  ["Overhyped", "Underappreciated"],
  ["Worst advice", "Best advice"],
  ["Failure", "Success"],
  ["Useless skill", "Useful skill"],
  ["Bad habit", "Good habit"],
  ["Waste of money", "Worth every penny"],
  ["Annoying", "Endearing"],

  // Best/Worst
  ["Bad movie", "Good movie"],
  ["Worst chore", "Best chore"],
  ["Bad superpower", "Good superpower"],
  ["Worst pizza topping", "Best pizza topping"],
  ["Bad gift", "Good gift"],
  ["Worst song to wake up to", "Best song to wake up to"],
  ["Bad date idea", "Good date idea"],
  ["Worst job", "Dream job"],
  ["Bad pet name", "Good pet name"],
  ["Worst holiday", "Best holiday"],
  ["Bad excuse", "Good excuse"],
  ["Worst way to travel", "Best way to travel"],
  ["Bad icebreaker", "Good icebreaker"],
  ["Worst smell", "Best smell"],
  ["Bad first impression", "Good first impression"],

  // Food
  ["Mild", "Spicy"],
  ["Snack", "Meal"],
  ["Unhealthy", "Healthy"],
  ["Breakfast food", "Dinner food"],
  ["Sweet", "Savory"],
  ["Comfort food", "Fancy food"],
  ["Disgusting combo", "Delicious combo"],
  ["Eat alone", "Share with friends"],
  ["Quick bite", "All-day cook"],
  ["Childhood food", "Adult food"],
  ["Overcooked", "Undercooked"],
  ["Street food", "Fine dining"],
  ["Guilty snack", "Virtuous snack"],
  ["Winter food", "Summer food"],
  ["Bland", "Flavorful"],

  // Culture
  ["Fantasy", "Sci-Fi"],
  ["Star Wars", "Star Trek"],
  ["For kids", "For adults"],
  ["Book was better", "Movie was better"],
  ["Indie", "Blockbuster"],
  ["Classic rock", "Modern pop"],
  ["Introvert activity", "Extrovert activity"],
  ["Morning person", "Night owl"],
  ["City life", "Country life"],
  ["Beach vacation", "Mountain vacation"],
  ["Cat person", "Dog person"],
  ["Reality TV", "Documentary"],
  ["Vinyl record", "Streaming"],
  ["Board game", "Video game"],
  ["Comedy", "Drama"],
  ["Halloween", "Christmas"],
  ["Coffee", "Tea"],
  ["Phone call", "Text message"],
  ["Online shopping", "In-store shopping"],
  ["Solo travel", "Group travel"],

  // Quirky
  ["Round animal", "Pointy animal"],
  ["Dog name", "Cat name"],
  ["Normal", "Weird"],
  ["Would survive a zombie apocalypse", "Would not survive"],
  ["Sounds like a band name", "Sounds like a law firm"],
  ["Looks easy", "Is actually easy"],
  ["Would make a good candle scent", "Would make a terrible candle scent"],
  ["Acceptable to do in public", "Only do at home"],
  ["Sounds real", "Sounds made up"],
  ["Kid thing", "Old person thing"],
  ["Would name a boat this", "Would never name a boat this"],
  ["Sounds like a compliment", "Sounds like an insult"],
  ["Fun fact", "Disturbing fact"],
  ["Would survive on a desert island", "Useless on a desert island"],
  ["Relaxing", "Stressful"],

  // Relationships & Social
  ["Red flag", "Green flag"],
  ["First date topic", "Never discuss on first date"],
  ["Romantic", "Unromantic"],
  ["Good wedding song", "Bad wedding song"],
  ["Party starter", "Party ender"],
  ["Friendship deal-breaker", "Friendship maker"],
  ["Awkward silence", "Comfortable silence"],
  ["Texts back immediately", "Takes days to reply"],
  ["Early to arrive", "Fashionably late"],
  ["Oversharer", "Keeps to themselves"],

  // Modern Life
  ["Worth the subscription", "Cancel immediately"],
  ["Should be automated", "Should stay manual"],
  ["Good use of AI", "Bad use of AI"],
  ["Should exist", "Should not exist"],
  ["Would go viral", "Nobody cares"],
  ["Peak internet", "Worst of internet"],
  ["Future looks bright", "Future looks bleak"],
  ["Millennials ruined it", "Millennials improved it"],
  ["Would tweet about it", "Would keep it private"],
  ["Zoom-friendly", "Must be in person"],

  // Abstract & Philosophical
  ["Means nothing", "Means everything"],
  ["Temporary", "Permanent"],
  ["Luck", "Skill"],
  ["Nature", "Nurture"],
  ["Art", "Science"],
  ["Journey", "Destination"],
  ["Quality", "Quantity"],
  ["Freedom", "Security"],
  ["Tradition", "Innovation"],
  ["Heart", "Head"],

  // Hypothetical
  ["Would time travel to the past", "Would time travel to the future"],
  ["Pick invisibility", "Pick flight"],
  ["Live in a movie", "Live in a TV show"],
  ["Would rather fight 1 horse-sized duck", "100 duck-sized horses"],
  ["Bring to a desert island", "Leave behind forever"],
  ["Teach to an alien", "Hide from an alien"],
  ["Would do for a million dollars", "Wouldn't do for any amount"],
  ["Want to know the answer", "Rather not know"],
  ["Would befriend in fiction", "Would avoid in fiction"],
  ["Perfect Monday", "Perfect Saturday"],

  // Nostalgia
  ["'90s", "2020s"],
  ["Childhood dream job", "Actual dream job"],
  ["Better when you were a kid", "Better as an adult"],
  ["Miss it", "Good riddance"],
  ["Timeless", "Dated"],
  ["First crush material", "Not first crush material"],
  ["School subject you loved", "School subject you dreaded"],
  ["Playground game", "Office game"],
  ["VHS era", "Streaming era"],
  ["Simpler times", "Modern convenience"],

  // Skills & Talents
  ["Natural talent", "Requires practice"],
  ["Impressive at parties", "Impressive on a resume"],
  ["Useful in everyday life", "Useful once a year"],
  ["Physical skill", "Mental skill"],
  ["Can learn from YouTube", "Need a teacher"],
  ["Peak at age 20", "Peak at age 60"],
  ["Solo skill", "Team skill"],
  ["Creative", "Analytical"],
  ["Underappreciated skill", "Gets too much credit"],
  ["Would show off", "Would keep secret"],

  // Sensory
  ["Sounds pleasant", "Sounds awful"],
  ["Smooth texture", "Rough texture"],
  ["Looks appetizing", "Looks unappetizing"],
  ["Smells like home", "Smells like danger"],
  ["Satisfying to touch", "Uncomfortable to touch"],
  ["Visually calming", "Visually chaotic"],
  ["ASMR-worthy", "Nails on a chalkboard"],
  ["Warm feeling", "Cool feeling"],
  ["Cozy aesthetic", "Sleek aesthetic"],
  ["Nostalgic sound", "Modern sound"],

  // Extra fun
  ["Florida Man headline", "Nobel Prize headline"],
  ["Good band name", "Bad band name"],
  ["Sounds expensive", "Sounds cheap"],
  ["Would name a child this", "Would never name a child this"],
  ["Conspiracy theory: plausible", "Conspiracy theory: ridiculous"],
  ["Renaissance painting subject", "Modern art subject"],
  ["Monopoly property you want", "Monopoly property you skip"],
  ["Elevator music", "Stadium anthem"],
  ["Plot of a rom-com", "Plot of a horror movie"],
  ["Belongs in a museum", "Belongs in the trash"],
];

export function getRandomSpectrums(count: number): [string, string][] {
  const shuffled = [...SPECTRUMS].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, count);
}
